services:
  cli-proxy-api:
    image: eceasy/cli-proxy-api-plus:latest
    pull_policy: always
    container_name: cli-proxy-api-plus
    ports:
      - "9999:8317"
    volumes:
      - ./config.yaml:/CLIProxyAPI/config.yaml
      - ./auths:/root/.cli-proxy-api
      - ./logs:/CLIProxyAPI/logs
    restart: unless-stopped